name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.21.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm lint

      - name: Type check
        run: pnpm --filter web exec tsc --noEmit

      - name: Build
        run: pnpm build
        env:
           NEXT_PUBLIC_SUPABASE_URL= https://mggeiewmexohvdnqjcac.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nZ2VpZXdtZXhvaHZkbnFqY2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU0MDI1MTQsImV4cCI6MjEwMDk3ODUxNH0.2wrI7s2NtZ4MqQyubq-m3L6eOuyXTyh4gYMdiElPHik